CREATE TABLE T_EMS_DEPARTMENT (
  ID   NUMBER(2) PRIMARY KEY,
  NAME VARCHAR2(20) NOT NULL
);

CREATE TABLE T_EMS_EMPLOYEE (
  ID       NUMBER(6) PRIMARY KEY,
  NAME     VARCHAR2(20)  NOT NULL,
  SEX      VARCHAR2(2)   NOT NULL,
  SALARY   NUMBER(10, 2) NOT NULL,
  BIRTHDAY DATE          NOT NULL,
  DEPT_ID  NUMBER(2) REFERENCES T_EMS_DEPARTMENT (ID)
);

CREATE TABLE T_EMS_ADMIN (
  NAME     VARCHAR2(20) PRIMARY KEY,
  PASSWORD VARCHAR2(32) NOT NULL,
  SALT     VARCHAR2(10) NOT NULL
);
DROP TABLE T_EMS_ADMIN;

CREATE SEQUENCE T_EMS_SEQ START WITH 100001 INCREMENT BY 1;

INSERT INTO T_EMS_DEPARTMENT VALUES (10, '销售部');
INSERT INTO T_EMS_DEPARTMENT VALUES (20, '后勤部');

INSERT INTO T_EMS_EMPLOYEE VALUES (T_EMS_SEQ.nextval, 'ZHANGSAN',
                                   'M', 4000, TO_DATE('1990-03-05', 'yyyy-mm-dd'), 20);
INSERT INTO T_EMS_EMPLOYEE VALUES (T_EMS_SEQ.nextval, 'LISI',
                                   'M', 6000, TO_DATE('1992-07-30', 'yyyy-mm-dd'), 10);
INSERT INTO T_EMS_EMPLOYEE VALUES (T_EMS_SEQ.nextval, 'WANGWU',
                                   'F', 5500, TO_DATE('1994-07-18', 'yyyy-mm-dd'), 20);
INSERT INTO T_EMS_EMPLOYEE VALUES (T_EMS_SEQ.nextval, 'LISI',
                                   'F', 2977, TO_DATE('1993-12-26', 'yyyy-mm-dd'), 10);

SELECT *
FROM T_EMS_DEPARTMENT;

SELECT *
FROM T_EMS_EMPLOYEE;

SELECT *
FROM T_EMS_ADMIN;

SELECT
  E.*,
  D.NAME
FROM T_EMS_EMPLOYEE E LEFT JOIN T_EMS_DEPARTMENT D
    ON E.DEPT_ID = D.ID;


DELETE FROM T_EMS_ADMIN;

SELECT *
FROM (SELECT
        E.*,
        D.NAME dname,
        ROWNUM rn
      FROM T_EMS_EMPLOYEE E
        LEFT JOIN T_EMS_DEPARTMENT D
          ON E.DEPT_ID = D.ID)


SELECT *         FROM T_EMS_ADMIN         WHERE NAME = 'me'